# Generated by Django 2.2.6 on 2019-10-24 02:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191024_0200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 24, 2, 1, 44, 200844, tzinfo=utc)),
        ),
    ]
