# Generated by Django 2.2.6 on 2019-10-25 05:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191025_0503'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 5, 18, 17, 972034, tzinfo=utc)),
        ),
    ]
