# Generated by Django 2.2.6 on 2019-10-25 10:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191025_0518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 25, 10, 37, 37, 812864, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='fb_id',
            field=models.CharField(db_index=True, editable=False, max_length=255, null=True, unique=True),
        ),
    ]
