# Generated by Django 2.2.6 on 2019-10-26 10:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20191026_1052'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ForgetPass',
            new_name='UserOTP',
        ),
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 26, 10, 52, 43, 846655, tzinfo=utc)),
        ),
    ]
