# Generated by Django 2.2.6 on 2019-10-27 09:00

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_auto_20191027_0841'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 9, 0, 5, 843604, tzinfo=utc)),
        ),
    ]
