# Generated by Django 2.2.6 on 2019-10-27 09:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191027_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 9, 18, 12, 265723, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='uid',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
