# Generated by Django 2.2.6 on 2019-10-27 10:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20191027_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 27, 10, 13, 23, 717414, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='userotp',
            name='uid',
            field=models.CharField(editable=False, max_length=255, primary_key=True, serialize=False),
        ),
    ]
