# Generated by Django 2.2.6 on 2019-11-03 17:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_auto_20191027_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 3, 17, 51, 30, 364235, tzinfo=utc)),
        ),
    ]
